---
- name: Remove unofficial docker packages
  ansible.builtin.apt:
    pkg:
      - docker.io
      - docker-doc
      - docker-compose
      - docker-compose-v2
      - podman-docker
      - containerd
      - runc
    state: absent
    update_cache: true

- name: Install prerequirements
  ansible.builtin.apt:
    pkg: 
     - gnupg2
    update_cache: yes

- name: Create the apt keyrings directory if it doesn't exist
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0644'

- name: Download the docker GPG apt key
  ansible.builtin.get_url:
    url: 'https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg'
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    force: true

- name: Get architecture
  command: 'dpkg --print-architecture'
  register: architecture_output

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: 'deb [arch={{ architecture_output }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable'
    state: present

- name: Update apt and install docker
  ansible.builtin.apt:
    pkg: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: true

- name: Add the user as a docker admin
  ansible.builtin.user:
    name: '{{ ansible_user }}'
    groups: docker
    append: yes
  when: add_user_as_docker_admin
