---
rocketpool_node:
  hosts:
    localhost: #If you are managing your node from another machine and running ansible on that computer replace "localhost" with the ip of your node.
      #ssh_public_key: ~/.ssh/id_rsa.pub #Uncomment this line if you want to deploy the specified ssh public key. This only makes sense if you are not running this on localhost.
      #ssh_backup_public_key: ~/.ssh/id_rsa_backup.pub # If you want to deploy a backup key, you can specify it here. Useful if you use yubikeys or manage your node from two remote computers.
      firewall_execution_client_port: 30303
      firewall_consensus_client_port: 9001
      #firewall_lighthouse_quick_port: 8001 # Uncomment this line if you are running the lighthouse consensus client, a rule will then be added to the firewall to allow the QUICK traffic
      #firewall_enable_exposing_fallback: true # Uncomment this line if you want to allow other nodes to connect and use the node as fallback
      #firewall_fallback_allowed_network: "10.1.1.0/24" # Optional firewall filter to set the source ip of those connecting to the fallback ports

nodeset_node:
  hosts:
    localhost: #If you are managing your node from another machine and running ansible on that computer replace "localhost" with the ip of your node.
      #ssh_public_key: ~/.ssh/id_rsa.pub # Uncomment this line if you want to deploy the specified ssh public key. This only makes sense if you are not running this on localhost.
      #ssh_backup_public_key: ~/.ssh/id_rsa_backup.pub # If you want to deploy a backup key, you can specify it here. Useful if you use yubikeys or manage your node from two remote computers.
      firewall_execution_client_port: 30303
      firewall_consensus_client_port: 9001
      #firewall_lighthouse_quick_port: 8001 # Uncomment this line if you are running the lighthouse consensus client, a rule will then be added to the firewall to allow the QUICK traffic
      #firewall_enable_exposing_fallback: true # Uncomment this line if you want to allow other nodes to connect and use the node as fallback
      #firewall_fallback_allowed_network: "10.1.1.0/24" # Optional firewall filter to set the source ip of those connecting to the fallback ports
